name: build
on:
  push:
    branches:
      - main
      - feature/deploy
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup ZDE
        uses: zoul0813/zeal-dev-environment/github/setup-zde@main
        with:
          deps: zgdk zar

      - name: Build with ZDE
        run: zde cmake

      - name: Stage binary
        run: cp bin/microbe.bin "${{ github.workspace }}/.deploy"

      - name: Deploy
        uses: ./.github/actions/deploy-pages

      # - name: Upload binaries
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: zshell-binaries
      #     path: |
      #       bin/zshell
      #       bin/default.img
